version: '3.1'

volumes:
  mysql_data:
  redis_data:

networks:
  backend:
  frontend:

services:
  mysql:
    image: mysql:5
    networks:
      - backend
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_USER: demo
      MYSQL_PASSWORD: 3x4mpl3
      MYSQL_DATABASE: demo_development
      MYSQL_ROOT_PASSWORD: 4dm1n15tr4t0r

  redis:
    image: redis:3-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/var/lib/redis
    command: redis-server --appendonly yes
    networks:
      - backend

  web:
    image: vovimayhem/php-demo:latest
    networks:
      - backend
      - frontend
    ports:
      - 80:8000
    command: php artisan serve --host=0.0.0.0 --port=8000
    depends_on:
      - mysql
    environment:
      APP_DEBUG: 'true'
      APP_LOG_LEVEL: debug

      APP_KEY: base64:5aoHpAok0Sjdq2Nhx44MvDzMcnAqZ/qzRxfHG++S8wU=

      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_DRIVER: redis

      REDIS_HOST: redis
      REDIS_PASSWORD: null
      REDIS_PORT: 6379

      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_USERNAME: demo
      DB_PASSWORD: 3x4mpl3
      DB_DATABASE: demo_development

      MAIL_DRIVER: smtp
      MAIL_HOST: mailtrap.io
      MAIL_PORT: 2525
      MAIL_USERNAME: null
      MAIL_PASSWORD: null
      MAIL_ENCRYPTION: null

      PUSHER_APP_ID:
      PUSHER_KEY:
      PUSHER_SECRET:
